#!/usr/bin/env bash
set -euo pipefail

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
status_file="$(mktemp)"
trap 'rm -f "$status_file"' EXIT

if [[ "${1:-}" != "--force" ]] && { [[ -f "$repo_dir/backend/.env" ]] || [[ -f "$repo_dir/frontend/.env.local" ]]; }; then
  echo "Local environment files already exist. Use --force to regenerate them."
  exit 1
fi

cd "$repo_dir"
supabase status -o env >"$status_file"
set -a
# The file is generated by the local Supabase CLI and contains shell-safe KEY=VALUE pairs.
source "$status_file"
set +a

download_secret="$(openssl rand -hex 32)"
encryption_secret="$(openssl rand -hex 32)"
soffice_path=""
while IFS= read -r candidate; do
  if [[ -x "$candidate" ]] && "$candidate" --version >/dev/null 2>&1; then
    soffice_path="$candidate"
    break
  fi
done < <(which -a soffice 2>/dev/null | awk '!seen[$0]++')

{
  printf 'PORT=3001\n'
  printf 'FRONTEND_URL=http://localhost:3000\n'
  printf 'DOWNLOAD_SIGNING_SECRET=%s\n' "$download_secret"
  printf 'SUPABASE_URL=%s\n' "$API_URL"
  printf 'SUPABASE_SECRET_KEY=%s\n' "$SECRET_KEY"
  printf 'R2_ENDPOINT_URL=%s\n' "$STORAGE_S3_URL"
  printf 'R2_ACCESS_KEY_ID=%s\n' "$S3_PROTOCOL_ACCESS_KEY_ID"
  printf 'R2_SECRET_ACCESS_KEY=%s\n' "$S3_PROTOCOL_ACCESS_KEY_SECRET"
  printf 'R2_BUCKET_NAME=mike-local\n'
  printf 'USER_API_KEYS_ENCRYPTION_SECRET=%s\n' "$encryption_secret"
  if [[ -n "$soffice_path" ]]; then
    printf 'SOFFICE_BINARY_PATH=%s\n' "$soffice_path"
  fi
} >"$repo_dir/backend/.env"

{
  printf 'NEXT_PUBLIC_SUPABASE_URL=%s\n' "$API_URL"
  printf 'NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY=%s\n' "$PUBLISHABLE_KEY"
  printf 'NEXT_PUBLIC_API_BASE_URL=http://localhost:3001\n'
  printf 'NEXT_PUBLIC_TERMS_URL=/support\n'
  printf 'NEXT_PUBLIC_PRIVACY_URL=/support\n'
} >"$repo_dir/frontend/.env.local"

bucket_status="$(curl --silent --output /dev/null --write-out '%{http_code}' \
  --request POST "$API_URL/storage/v1/bucket" \
  --header "Authorization: Bearer $SECRET_KEY" \
  --header "apikey: $SECRET_KEY" \
  --header 'Content-Type: application/json' \
  --data '{"id":"mike-local","name":"mike-local","public":false}')"

if [[ "$bucket_status" != "200" ]] && [[ "$bucket_status" != "400" ]]; then
  echo "Failed to create the local object-storage bucket (HTTP $bucket_status)."
  exit 1
fi

echo "Local Mike environment is ready. No model-provider key was written."
